--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,4 +17,4 @@
           -skipMacroValidation
           -sdk iphonesimulator
           -scheme ${{ env.SCHEME_NAME }}
-          -destination 'platform=iOS Simulator,name=iPhone 15 Pro'
+          -destination 'platform=iOS Simulator,name=iPhone 15 Pro'